<?php

define('PHP_OUTPUT_HANDLER_START', 0);
define('PHP_OUTPUT_HANDLER_WRITE', 0);
define('PHP_OUTPUT_HANDLER_FLUSH', 0);
define('PHP_OUTPUT_HANDLER_CLEAN', 0);
define('PHP_OUTPUT_HANDLER_FINAL', 0);
define('PHP_OUTPUT_HANDLER_CONT', 0);
define('PHP_OUTPUT_HANDLER_END', 0);
define('PHP_OUTPUT_HANDLER_CLEANABLE', 0);
define('PHP_OUTPUT_HANDLER_FLUSHABLE', 0);
define('PHP_OUTPUT_HANDLER_REMOVABLE', 0);
define('PHP_OUTPUT_HANDLER_STDFLAGS', 0);
