<?php

define('PTHREADS_INHERIT_ALL', 0);
define('PTHREADS_INHERIT_NONE', 0);
define('PTHREADS_INHERIT_INI', 0);
define('PTHREADS_INHERIT_CONSTANTS', 0);
define('PTHREADS_INHERIT_CLASSES', 0);
define('PTHREADS_INHERIT_FUNCTIONS', 0);
define('PTHREADS_INHERIT_INCLUDES', 0);
define('PTHREADS_INHERIT_COMMENTS', 0);
define('PTHREADS_ALLOW_HEADERS', 0);
