<?php

define('MONGO_STREAMS', 0);
define('MONGO_SUPPORTS_STREAMS', 0);
define('MONGO_SUPPORTS_SSL', 0);
define('MONGO_SUPPORTS_AUTH_MECHANISM_MONGODB_CR', 0);
define('MONGO_SUPPORTS_AUTH_MECHANISM_MONGODB_X509', 0);
define('MONGO_SUPPORTS_AUTH_MECHANISM_GSSAPI', 0);
define('MONGO_SUPPORTS_AUTH_MECHANISM_PLAIN', 0);
define('MONGO_STREAM_NOTIFY_TYPE_IO_INIT', 0);
define('MONGO_STREAM_NOTIFY_TYPE_LOG', 0);
define('MONGO_STREAM_NOTIFY_IO_READ', 0);
define('MONGO_STREAM_NOTIFY_IO_WRITE', 0);
define('MONGO_STREAM_NOTIFY_IO_PROGRESS', 0);
define('MONGO_STREAM_NOTIFY_IO_COMPLETED', 0);
define('MONGO_STREAM_NOTIFY_LOG_INSERT', 0);
define('MONGO_STREAM_NOTIFY_LOG_QUERY', 0);
define('MONGO_STREAM_NOTIFY_LOG_UPDATE', 0);
define('MONGO_STREAM_NOTIFY_LOG_DELETE', 0);
define('MONGO_STREAM_NOTIFY_LOG_GETMORE', 0);
define('MONGO_STREAM_NOTIFY_LOG_KILLCURSOR', 0);
define('MONGO_STREAM_NOTIFY_LOG_BATCHINSERT', 0);
define('MONGO_STREAM_NOTIFY_LOG_RESPONSE_HEADER', 0);
define('MONGO_STREAM_NOTIFY_LOG_WRITE_REPLY', 0);
define('MONGO_STREAM_NOTIFY_LOG_CMD_INSERT', 0);
define('MONGO_STREAM_NOTIFY_LOG_CMD_UPDATE', 0);
define('MONGO_STREAM_NOTIFY_LOG_CMD_DELETE', 0);
define('MONGO_STREAM_NOTIFY_LOG_WRITE_BATCH', 0);
